

--##################################################### 
--# Database DDL 
--##################################################### 


SET SESSION AUTHORIZATION "SYS"; 
COMMENT 
    ON DATABASE 
    IS 'goldilocks database' 
;
COMMIT;

--##################################################### 
--# Tablespace DDL 
--##################################################### 


--##################################################### 
--# Profile DDL 
--##################################################### 


SET SESSION AUTHORIZATION "SYS"; 
ALTER PROFILE "DEFAULT" LIMIT 
    FAILED_LOGIN_ATTEMPTS   10 
    PASSWORD_LOCK_TIME   1 
    PASSWORD_LIFE_TIME   180 
    PASSWORD_GRACE_TIME   7 
    PASSWORD_REUSE_MAX   UNLIMITED 
    PASSWORD_REUSE_TIME   UNLIMITED 
    PASSWORD_VERIFY_FUNCTION   NULL 
;
COMMIT;

--##################################################### 
--# Authorization DDL 
--##################################################### 


SET SESSION AUTHORIZATION "SYS"; 
ALTER USER "SYS" 
    DEFAULT TABLESPACE "MEM_DATA_TBS" 
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
ALTER USER "SYS" 
    TEMPORARY TABLESPACE "MEM_TEMP_TBS" 
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
ALTER USER "SYS" 
    INDEX TABLESPACE NULL 
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
ALTER USER "TEST" 
    DEFAULT TABLESPACE "MEM_DATA_TBS" 
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
ALTER USER "TEST" 
    TEMPORARY TABLESPACE "MEM_TEMP_TBS" 
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
ALTER USER "TEST" 
    INDEX TABLESPACE NULL 
;
COMMIT;

--##################################################### 
--# Schema DDL 
--##################################################### 


--##################################################### 
--# Authorization Schema Path DDL 
--##################################################### 


SET SESSION AUTHORIZATION "SYS"; 
ALTER USER "SYS" 
    SCHEMA PATH 
    ( 
        "PUBLIC" 
      , "DICTIONARY_SCHEMA" 
      , "INFORMATION_SCHEMA" 
      , "DEFINITION_SCHEMA" 
      , "PERFORMANCE_VIEW_SCHEMA" 
      , "FIXED_TABLE_SCHEMA" 
    ) 
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
ALTER USER "PUBLIC" 
    SCHEMA PATH 
    ( 
        "DICTIONARY_SCHEMA" 
      , "INFORMATION_SCHEMA" 
      , "DEFINITION_SCHEMA" 
      , "PERFORMANCE_VIEW_SCHEMA" 
      , "FIXED_TABLE_SCHEMA" 
    ) 
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
ALTER USER "TEST" 
    SCHEMA PATH 
    ( 
        "PUBLIC" 
    ) 
;
COMMIT;

--##################################################### 
--# Database Privilege DDL 
--##################################################### 


--##################################################### 
--# Tablespace Privilege DDL 
--##################################################### 


--##################################################### 
--# Schema Privilege DDL 
--##################################################### 


--##################################################### 
--# Public Synonym DDL 
--##################################################### 


SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DUAL" FOR "FIXED_TABLE_SCHEMA"."DUAL"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_ALL_TABLES" FOR "DICTIONARY_SCHEMA"."DBA_ALL_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_ALL_TABLES" FOR "DICTIONARY_SCHEMA"."ALL_ALL_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_ALL_TABLES" FOR "DICTIONARY_SCHEMA"."USER_ALL_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_COL_COMMENTS" FOR "DICTIONARY_SCHEMA"."DBA_COL_COMMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_COL_COMMENTS" FOR "DICTIONARY_SCHEMA"."ALL_COL_COMMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_COL_COMMENTS" FOR "DICTIONARY_SCHEMA"."USER_COL_COMMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_COL_PRIVS" FOR "DICTIONARY_SCHEMA"."DBA_COL_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_COL_PRIVS" FOR "DICTIONARY_SCHEMA"."ALL_COL_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_COL_PRIVS" FOR "DICTIONARY_SCHEMA"."USER_COL_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_COL_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."ALL_COL_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_COL_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."USER_COL_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_COL_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."ALL_COL_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_COL_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."USER_COL_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_CONSTRAINTS" FOR "DICTIONARY_SCHEMA"."DBA_CONSTRAINTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_CONSTRAINTS" FOR "DICTIONARY_SCHEMA"."ALL_CONSTRAINTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_CONSTRAINTS" FOR "DICTIONARY_SCHEMA"."USER_CONSTRAINTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_CONS_COLUMNS" FOR "DICTIONARY_SCHEMA"."DBA_CONS_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_CONS_COLUMNS" FOR "DICTIONARY_SCHEMA"."ALL_CONS_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_CONS_COLUMNS" FOR "DICTIONARY_SCHEMA"."USER_CONS_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_DB_PRIVS" FOR "DICTIONARY_SCHEMA"."DBA_DB_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_DB_PRIVS" FOR "DICTIONARY_SCHEMA"."ALL_DB_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_DB_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."ALL_DB_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_DB_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."ALL_DB_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_EXTENTS" FOR "DICTIONARY_SCHEMA"."DBA_EXTENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_EXTENTS" FOR "DICTIONARY_SCHEMA"."USER_EXTENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_INDEXES" FOR "DICTIONARY_SCHEMA"."DBA_INDEXES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_INDEXES" FOR "DICTIONARY_SCHEMA"."ALL_INDEXES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_INDEXES" FOR "DICTIONARY_SCHEMA"."USER_INDEXES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "IND" FOR "DICTIONARY_SCHEMA"."USER_INDEXES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_IND_COLUMNS" FOR "DICTIONARY_SCHEMA"."DBA_IND_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_IND_COLUMNS" FOR "DICTIONARY_SCHEMA"."ALL_IND_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_IND_COLUMNS" FOR "DICTIONARY_SCHEMA"."USER_IND_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_NONSCHEMA_COMMENTS" FOR "DICTIONARY_SCHEMA"."DBA_NONSCHEMA_COMMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_NONSCHEMA_COMMENTS" FOR "DICTIONARY_SCHEMA"."ALL_NONSCHEMA_COMMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_OBJECTS" FOR "DICTIONARY_SCHEMA"."DBA_OBJECTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_OBJECTS" FOR "DICTIONARY_SCHEMA"."ALL_OBJECTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_OBJECTS" FOR "DICTIONARY_SCHEMA"."USER_OBJECTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "OBJ" FOR "DICTIONARY_SCHEMA"."USER_OBJECTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_CATALOG" FOR "DICTIONARY_SCHEMA"."DBA_CATALOG"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_CATALOG" FOR "DICTIONARY_SCHEMA"."ALL_CATALOG"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_CATALOG" FOR "DICTIONARY_SCHEMA"."USER_CATALOG"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_PROFILES" FOR "DICTIONARY_SCHEMA"."DBA_PROFILES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_SCHEMAS" FOR "DICTIONARY_SCHEMA"."DBA_SCHEMAS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SCHEMAS" FOR "DICTIONARY_SCHEMA"."ALL_SCHEMAS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SCHEMAS" FOR "DICTIONARY_SCHEMA"."USER_SCHEMAS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_SCHEMA_PATH" FOR "DICTIONARY_SCHEMA"."DBA_SCHEMA_PATH"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SCHEMA_PATH" FOR "DICTIONARY_SCHEMA"."ALL_SCHEMA_PATH"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SCHEMA_PATH" FOR "DICTIONARY_SCHEMA"."USER_SCHEMA_PATH"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_SCHEMA_PRIVS" FOR "DICTIONARY_SCHEMA"."DBA_SCHEMA_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SCHEMA_PRIVS" FOR "DICTIONARY_SCHEMA"."ALL_SCHEMA_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SCHEMA_PRIVS" FOR "DICTIONARY_SCHEMA"."USER_SCHEMA_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SCHEMA_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."ALL_SCHEMA_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SCHEMA_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."USER_SCHEMA_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SCHEMA_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."ALL_SCHEMA_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SCHEMA_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."USER_SCHEMA_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_SEQUENCES" FOR "DICTIONARY_SCHEMA"."DBA_SEQUENCES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SEQUENCES" FOR "DICTIONARY_SCHEMA"."ALL_SEQUENCES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SEQUENCES" FOR "DICTIONARY_SCHEMA"."USER_SEQUENCES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SEQ" FOR "DICTIONARY_SCHEMA"."USER_SEQUENCES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_SEQ_PRIVS" FOR "DICTIONARY_SCHEMA"."DBA_SEQ_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SEQ_PRIVS" FOR "DICTIONARY_SCHEMA"."ALL_SEQ_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SEQ_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."ALL_SEQ_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SEQ_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."USER_SEQ_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SEQ_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."ALL_SEQ_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SEQ_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."USER_SEQ_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SEQ_PRIVS" FOR "DICTIONARY_SCHEMA"."USER_SEQ_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TABLES" FOR "DICTIONARY_SCHEMA"."DBA_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TABLES" FOR "DICTIONARY_SCHEMA"."ALL_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TABLES" FOR "DICTIONARY_SCHEMA"."USER_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "TABS" FOR "DICTIONARY_SCHEMA"."USER_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TAB_COLS" FOR "DICTIONARY_SCHEMA"."DBA_TAB_COLS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TAB_COLS" FOR "DICTIONARY_SCHEMA"."ALL_TAB_COLS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TAB_COLS" FOR "DICTIONARY_SCHEMA"."USER_TAB_COLS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TAB_COLUMNS" FOR "DICTIONARY_SCHEMA"."DBA_TAB_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TAB_COLUMNS" FOR "DICTIONARY_SCHEMA"."ALL_TAB_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TAB_COLUMNS" FOR "DICTIONARY_SCHEMA"."USER_TAB_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "COLS" FOR "DICTIONARY_SCHEMA"."USER_TAB_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TAB_COMMENTS" FOR "DICTIONARY_SCHEMA"."DBA_TAB_COMMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TAB_COMMENTS" FOR "DICTIONARY_SCHEMA"."ALL_TAB_COMMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TAB_COMMENTS" FOR "DICTIONARY_SCHEMA"."USER_TAB_COMMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TAB_IDENTITY_COLS" FOR "DICTIONARY_SCHEMA"."DBA_TAB_IDENTITY_COLS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TAB_IDENTITY_COLS" FOR "DICTIONARY_SCHEMA"."ALL_TAB_IDENTITY_COLS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TAB_IDENTITY_COLS" FOR "DICTIONARY_SCHEMA"."USER_TAB_IDENTITY_COLS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TABLESPACES" FOR "DICTIONARY_SCHEMA"."DBA_TABLESPACES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TABLESPACES" FOR "DICTIONARY_SCHEMA"."USER_TABLESPACES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TAB_PRIVS" FOR "DICTIONARY_SCHEMA"."DBA_TAB_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TAB_PRIVS" FOR "DICTIONARY_SCHEMA"."ALL_TAB_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TAB_PRIVS" FOR "DICTIONARY_SCHEMA"."USER_TAB_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TAB_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."ALL_TAB_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TAB_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."USER_TAB_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TAB_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."ALL_TAB_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TAB_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."USER_TAB_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TBS_PRIVS" FOR "DICTIONARY_SCHEMA"."DBA_TBS_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TBS_PRIVS" FOR "DICTIONARY_SCHEMA"."ALL_TBS_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TBS_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."ALL_TBS_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TBS_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."ALL_TBS_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_SYS_PRIVS" FOR "DICTIONARY_SCHEMA"."DBA_SYS_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SYS_PRIVS" FOR "DICTIONARY_SCHEMA"."USER_SYS_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_VIEWS" FOR "DICTIONARY_SCHEMA"."DBA_VIEWS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_VIEWS" FOR "DICTIONARY_SCHEMA"."ALL_VIEWS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_VIEWS" FOR "DICTIONARY_SCHEMA"."USER_VIEWS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_USERS" FOR "DICTIONARY_SCHEMA"."DBA_USERS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_USERS" FOR "DICTIONARY_SCHEMA"."ALL_USERS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_USERS" FOR "DICTIONARY_SCHEMA"."USER_USERS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_SYNONYMS" FOR "DICTIONARY_SCHEMA"."DBA_SYNONYMS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SYNONYMS" FOR "DICTIONARY_SCHEMA"."ALL_SYNONYMS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SYNONYMS" FOR "DICTIONARY_SCHEMA"."USER_SYNONYMS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_STAT_SYSTEM" FOR "DICTIONARY_SCHEMA"."DBA_STAT_SYSTEM"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DATABASE_PROPERTIES" FOR "DICTIONARY_SCHEMA"."DATABASE_PROPERTIES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_TABLE_TYPE_INFO" FOR "DICTIONARY_SCHEMA"."DBC_TABLE_TYPE_INFO"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DICTIONARY" FOR "DICTIONARY_SCHEMA"."DICTIONARY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DICT" FOR "DICTIONARY_SCHEMA"."DICTIONARY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DICT_COLUMNS" FOR "DICTIONARY_SCHEMA"."DICT_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "JDBC_CLIENT_PROPS" FOR "DICTIONARY_SCHEMA"."JDBC_CLIENT_PROPS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "PRODUCT" FOR "DICTIONARY_SCHEMA"."PRODUCT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SESSION_PRIVS" FOR "DICTIONARY_SCHEMA"."SESSION_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "IMPLEMENTATION_INFO_BASE" FOR "DICTIONARY_SCHEMA"."IMPLEMENTATION_INFO_BASE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "IMPLEMENTATION_INFO" FOR "DICTIONARY_SCHEMA"."IMPLEMENTATION_INFO"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SUPPLEMENTAL_LOG_TABLE_INFO" FOR "DICTIONARY_SCHEMA"."SUPPLEMENTAL_LOG_TABLE_INFO"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_CLUSTER" FOR "DICTIONARY_SCHEMA"."DBA_CLUSTER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_CLUSTER_COMMENTS" FOR "DICTIONARY_SCHEMA"."DBA_CLUSTER_COMMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_CLUSTER_TABLES" FOR "DICTIONARY_SCHEMA"."DBA_CLUSTER_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_CLUSTER_TABLES" FOR "DICTIONARY_SCHEMA"."ALL_CLUSTER_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_CLUSTER_TABLES" FOR "DICTIONARY_SCHEMA"."USER_CLUSTER_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_GLOBAL_SECONDARY_INDEXES" FOR "DICTIONARY_SCHEMA"."DBA_GLOBAL_SECONDARY_INDEXES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_GLOBAL_SECONDARY_INDEXES" FOR "DICTIONARY_SCHEMA"."ALL_GLOBAL_SECONDARY_INDEXES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_GLOBAL_SECONDARY_INDEXES" FOR "DICTIONARY_SCHEMA"."USER_GLOBAL_SECONDARY_INDEXES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_SHARD_KEY_COLUMNS" FOR "DICTIONARY_SCHEMA"."DBA_SHARD_KEY_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SHARD_KEY_COLUMNS" FOR "DICTIONARY_SCHEMA"."ALL_SHARD_KEY_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SHARD_KEY_COLUMNS" FOR "DICTIONARY_SCHEMA"."USER_SHARD_KEY_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TAB_PLACE" FOR "DICTIONARY_SCHEMA"."DBA_TAB_PLACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TAB_PLACE" FOR "DICTIONARY_SCHEMA"."ALL_TAB_PLACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TAB_PLACE" FOR "DICTIONARY_SCHEMA"."USER_TAB_PLACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_IND_PLACE" FOR "DICTIONARY_SCHEMA"."DBA_IND_PLACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_IND_PLACE" FOR "DICTIONARY_SCHEMA"."ALL_IND_PLACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_IND_PLACE" FOR "DICTIONARY_SCHEMA"."USER_IND_PLACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_GSI_PLACE" FOR "DICTIONARY_SCHEMA"."DBA_GSI_PLACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_GSI_PLACE" FOR "DICTIONARY_SCHEMA"."ALL_GSI_PLACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_GSI_PLACE" FOR "DICTIONARY_SCHEMA"."USER_GSI_PLACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_TAB_SHARDS" FOR "DICTIONARY_SCHEMA"."DBA_TAB_SHARDS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_TAB_SHARDS" FOR "DICTIONARY_SCHEMA"."ALL_TAB_SHARDS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_TAB_SHARDS" FOR "DICTIONARY_SCHEMA"."USER_TAB_SHARDS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_PROCEDURES" FOR "DICTIONARY_SCHEMA"."DBA_PROCEDURES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_PROCEDURES" FOR "DICTIONARY_SCHEMA"."ALL_PROCEDURES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_PROCEDURES" FOR "DICTIONARY_SCHEMA"."USER_PROCEDURES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_ARGUMENTS" FOR "DICTIONARY_SCHEMA"."DBA_ARGUMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_ARGUMENTS" FOR "DICTIONARY_SCHEMA"."ALL_ARGUMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_ARGUMENTS" FOR "DICTIONARY_SCHEMA"."USER_ARGUMENTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_SOURCE" FOR "DICTIONARY_SCHEMA"."DBA_SOURCE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_SOURCE" FOR "DICTIONARY_SCHEMA"."ALL_SOURCE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_SOURCE" FOR "DICTIONARY_SCHEMA"."USER_SOURCE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_DEPENDENCIES" FOR "DICTIONARY_SCHEMA"."DBA_DEPENDENCIES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_DEPENDENCIES" FOR "DICTIONARY_SCHEMA"."ALL_DEPENDENCIES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_DEPENDENCIES" FOR "DICTIONARY_SCHEMA"."USER_DEPENDENCIES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_PROC_PRIVS" FOR "DICTIONARY_SCHEMA"."DBA_PROC_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_PROC_PRIVS" FOR "DICTIONARY_SCHEMA"."ALL_PROC_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_PROC_PRIVS" FOR "DICTIONARY_SCHEMA"."USER_PROC_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_PROC_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."ALL_PROC_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_PROC_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."USER_PROC_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_PROC_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."ALL_PROC_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_PROC_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."USER_PROC_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_PACKAGE_PRIVS" FOR "DICTIONARY_SCHEMA"."DBA_PACKAGE_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_PACKAGE_PRIVS" FOR "DICTIONARY_SCHEMA"."ALL_PACKAGE_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_PACKAGE_PRIVS" FOR "DICTIONARY_SCHEMA"."USER_PACKAGE_PRIVS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_PACKAGE_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."ALL_PACKAGE_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_PACKAGE_PRIVS_MADE" FOR "DICTIONARY_SCHEMA"."USER_PACKAGE_PRIVS_MADE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ALL_PACKAGE_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."ALL_PACKAGE_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_PACKAGE_PRIVS_RECD" FOR "DICTIONARY_SCHEMA"."USER_PACKAGE_PRIVS_RECD"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "AUDIT_POLICIES" FOR "DICTIONARY_SCHEMA"."AUDIT_POLICIES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "AUDIT_POLICY_OPTIONS" FOR "DICTIONARY_SCHEMA"."AUDIT_POLICY_OPTIONS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "AUDIT_POLICY_ENABLED" FOR "DICTIONARY_SCHEMA"."AUDIT_POLICY_ENABLED"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "AUDIT_TRAIL" FOR "DICTIONARY_SCHEMA"."AUDIT_TRAIL"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBA_RECYCLEBIN" FOR "DICTIONARY_SCHEMA"."DBA_RECYCLEBIN"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USER_RECYCLEBIN" FOR "DICTIONARY_SCHEMA"."USER_RECYCLEBIN"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "RECYCLEBIN" FOR "DICTIONARY_SCHEMA"."USER_RECYCLEBIN"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "COLUMNS" FOR "INFORMATION_SCHEMA"."COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "COLUMN_PRIVILEGES" FOR "INFORMATION_SCHEMA"."COLUMN_PRIVILEGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "CONSTRAINT_COLUMN_USAGE" FOR "INFORMATION_SCHEMA"."CONSTRAINT_COLUMN_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "CONSTRAINT_TABLE_USAGE" FOR "INFORMATION_SCHEMA"."CONSTRAINT_TABLE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "INFORMATION_SCHEMA_CATALOG_NAME" FOR "INFORMATION_SCHEMA"."INFORMATION_SCHEMA_CATALOG_NAME"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "KEY_COLUMN_USAGE" FOR "INFORMATION_SCHEMA"."KEY_COLUMN_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "REFERENTIAL_CONSTRAINTS" FOR "INFORMATION_SCHEMA"."REFERENTIAL_CONSTRAINTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SCHEMATA" FOR "INFORMATION_SCHEMA"."SCHEMATA"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SEQUENCES" FOR "INFORMATION_SCHEMA"."SEQUENCES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SQL_FEATURES" FOR "INFORMATION_SCHEMA"."SQL_FEATURES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SQL_IMPLEMENTATION_INFO" FOR "INFORMATION_SCHEMA"."SQL_IMPLEMENTATION_INFO"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SQL_PACKAGES" FOR "INFORMATION_SCHEMA"."SQL_PACKAGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SQL_PARTS" FOR "INFORMATION_SCHEMA"."SQL_PARTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "SQL_SIZING" FOR "INFORMATION_SCHEMA"."SQL_SIZING"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "STATISTICS" FOR "INFORMATION_SCHEMA"."STATISTICS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "TABLES" FOR "INFORMATION_SCHEMA"."TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "TABLE_CONSTRAINTS" FOR "INFORMATION_SCHEMA"."TABLE_CONSTRAINTS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "TABLE_PRIVILEGES" FOR "INFORMATION_SCHEMA"."TABLE_PRIVILEGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "USAGE_PRIVILEGES" FOR "INFORMATION_SCHEMA"."USAGE_PRIVILEGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "VIEWS" FOR "INFORMATION_SCHEMA"."VIEWS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "VIEW_TABLE_USAGE" FOR "INFORMATION_SCHEMA"."VIEW_TABLE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "VIEW_ROUTINE_USAGE" FOR "INFORMATION_SCHEMA"."VIEW_ROUTINE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ROUTINES" FOR "INFORMATION_SCHEMA"."ROUTINES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "PARAMETERS" FOR "INFORMATION_SCHEMA"."PARAMETERS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ROUTINE_PRIVILEGES" FOR "INFORMATION_SCHEMA"."ROUTINE_PRIVILEGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ROUTINE_ROUTINE_USAGE" FOR "INFORMATION_SCHEMA"."ROUTINE_ROUTINE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ROUTINE_SEQUENCE_USAGE" FOR "INFORMATION_SCHEMA"."ROUTINE_SEQUENCE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ROUTINE_TABLE_USAGE" FOR "INFORMATION_SCHEMA"."ROUTINE_TABLE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_TABLES" FOR "INFORMATION_SCHEMA"."DBC_TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_COLUMNS" FOR "INFORMATION_SCHEMA"."DBC_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_COLUMNS_WITH_SYNONYMS" FOR "INFORMATION_SCHEMA"."DBC_COLUMNS_WITH_SYNONYMS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_PRIMARY_KEYS" FOR "INFORMATION_SCHEMA"."DBC_PRIMARY_KEYS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_FOREIGN_KEYS" FOR "INFORMATION_SCHEMA"."DBC_FOREIGN_KEYS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_STATISTICS" FOR "INFORMATION_SCHEMA"."DBC_STATISTICS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_TABLE_PRIVILEGES" FOR "INFORMATION_SCHEMA"."DBC_TABLE_PRIVILEGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_COLUMN_PRIVILEGES" FOR "INFORMATION_SCHEMA"."DBC_COLUMN_PRIVILEGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_PROCEDURES" FOR "INFORMATION_SCHEMA"."DBC_PROCEDURES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "DBC_PROCEDURE_COLUMNS" FOR "INFORMATION_SCHEMA"."DBC_PROCEDURE_COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULES" FOR "INFORMATION_SCHEMA"."MODULES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_PRIVILEGES" FOR "INFORMATION_SCHEMA"."MODULE_PRIVILEGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_TABLE_USAGE" FOR "INFORMATION_SCHEMA"."MODULE_TABLE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_MODULE_USAGE" FOR "INFORMATION_SCHEMA"."MODULE_MODULE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_ROUTINE_USAGE" FOR "INFORMATION_SCHEMA"."MODULE_ROUTINE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_SEQUENCE_USAGE" FOR "INFORMATION_SCHEMA"."MODULE_SEQUENCE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_BODY" FOR "INFORMATION_SCHEMA"."MODULE_BODY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_BODY_TABLE_USAGE" FOR "INFORMATION_SCHEMA"."MODULE_BODY_TABLE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_BODY_MODULE_USAGE" FOR "INFORMATION_SCHEMA"."MODULE_BODY_MODULE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_BODY_ROUTINE_USAGE" FOR "INFORMATION_SCHEMA"."MODULE_BODY_ROUTINE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "MODULE_BODY_SEQUENCE_USAGE" FOR "INFORMATION_SCHEMA"."MODULE_BODY_SEQUENCE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "VIEW_MODULE_USAGE" FOR "INFORMATION_SCHEMA"."VIEW_MODULE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "ROUTINE_MODULE_USAGE" FOR "INFORMATION_SCHEMA"."ROUTINE_MODULE_USAGE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$ARCHIVELOG" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$ARCHIVELOG"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$ARCHIVELOG" FOR "PERFORMANCE_VIEW_SCHEMA"."V$ARCHIVELOG"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$BACKUP" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$BACKUP"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$BACKUP" FOR "PERFORMANCE_VIEW_SCHEMA"."V$BACKUP"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$COLUMNS" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$COLUMNS" FOR "PERFORMANCE_VIEW_SCHEMA"."V$COLUMNS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$DATAFILE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$DATAFILE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$DATAFILE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$DATAFILE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$ERROR_CODE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$ERROR_CODE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$ERROR_CODE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$ERROR_CODE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$XA_TRANSACTION" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$XA_TRANSACTION"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$XA_TRANSACTION" FOR "PERFORMANCE_VIEW_SCHEMA"."V$XA_TRANSACTION"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$INCREMENTAL_BACKUP" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$INCREMENTAL_BACKUP"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$INCREMENTAL_BACKUP" FOR "PERFORMANCE_VIEW_SCHEMA"."V$INCREMENTAL_BACKUP"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$KEYWORDS" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$KEYWORDS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$KEYWORDS" FOR "PERFORMANCE_VIEW_SCHEMA"."V$KEYWORDS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$LATCH" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$LATCH"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$LATCH" FOR "PERFORMANCE_VIEW_SCHEMA"."V$LATCH"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$LOGFILE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$LOGFILE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$LOGFILE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$LOGFILE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$LOCK_WAIT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$LOCK_WAIT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$LOCK_WAIT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$LOCK_WAIT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$PROPERTY" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$PROPERTY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$PROPERTY" FOR "PERFORMANCE_VIEW_SCHEMA"."V$PROPERTY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$PROCESS_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$PROCESS_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$PROCESS_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$PROCESS_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$PROCESS_MEM_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$PROCESS_MEM_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$PROCESS_MEM_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$PROCESS_MEM_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$PROCESS_SQL_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$PROCESS_SQL_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$PROCESS_SQL_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$PROCESS_SQL_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$PSM_RESERVED_WORDS" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$PSM_RESERVED_WORDS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$PSM_RESERVED_WORDS" FOR "PERFORMANCE_VIEW_SCHEMA"."V$PSM_RESERVED_WORDS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$RESERVED_WORDS" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$RESERVED_WORDS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$RESERVED_WORDS" FOR "PERFORMANCE_VIEW_SCHEMA"."V$RESERVED_WORDS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SESSION" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SESSION"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SESSION" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SESSION"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SESSION_AUDIT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SESSION_AUDIT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SESSION_AUDIT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SESSION_AUDIT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SESSION_CONNECT_INFO" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SESSION_CONNECT_INFO"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SESSION_CONNECT_INFO" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SESSION_CONNECT_INFO"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SESSION_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SESSION_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SESSION_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SESSION_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SESSION_MEM_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SESSION_MEM_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SESSION_MEM_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SESSION_MEM_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SESSION_SQL_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SESSION_SQL_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SESSION_SQL_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SESSION_SQL_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SHM_SEGMENT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SHM_SEGMENT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SHM_SEGMENT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SHM_SEGMENT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SQLFN_METADATA" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SQLFN_METADATA"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SQLFN_METADATA" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SQLFN_METADATA"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SQL_CACHE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SQL_CACHE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SQL_CACHE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SQL_CACHE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SQL_COMMAND" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SQL_COMMAND"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SQL_COMMAND" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SQL_COMMAND"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$STATEMENT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$STATEMENT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$STATEMENT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$STATEMENT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SPROPERTY" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SPROPERTY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SPROPERTY" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SPROPERTY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SYSTEM_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SYSTEM_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SYSTEM_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SYSTEM_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SYSTEM_MEM_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SYSTEM_MEM_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SYSTEM_SQL_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SYSTEM_SQL_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SYSTEM_SQL_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SYSTEM_SQL_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$TABLES" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$TABLES" FOR "PERFORMANCE_VIEW_SCHEMA"."V$TABLES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$TABLESPACE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$TABLESPACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$TABLESPACE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$TABLESPACE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$TABLESPACE_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$TABLESPACE_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$TABLESPACE_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$TABLESPACE_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$TRANSACTION" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$TRANSACTION"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$TRANSACTION" FOR "PERFORMANCE_VIEW_SCHEMA"."V$TRANSACTION"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$INSTANCE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$INSTANCE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$INSTANCE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$INSTANCE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$CONTROLFILE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$CONTROLFILE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$CONTROLFILE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$CONTROLFILE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$DB_FILE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$DB_FILE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$DB_FILE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$DB_FILE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SHARED_MODE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SHARED_MODE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SHARED_MODE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SHARED_MODE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$DISPATCHER" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$DISPATCHER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$DISPATCHER" FOR "PERFORMANCE_VIEW_SCHEMA"."V$DISPATCHER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SHARED_SERVER" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SHARED_SERVER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SHARED_SERVER" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SHARED_SERVER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$BALANCER" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$BALANCER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$BALANCER" FOR "PERFORMANCE_VIEW_SCHEMA"."V$BALANCER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$QUEUE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$QUEUE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$QUEUE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$QUEUE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$JOURNALING" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$JOURNALING"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$JOURNALING" FOR "PERFORMANCE_VIEW_SCHEMA"."V$JOURNALING"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$CLUSTER_MEMBER" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$CLUSTER_MEMBER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$CLUSTER_MEMBER" FOR "PERFORMANCE_VIEW_SCHEMA"."V$CLUSTER_MEMBER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$CLUSTER_DISPATCHER" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$CLUSTER_DISPATCHER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$CLUSTER_DISPATCHER" FOR "PERFORMANCE_VIEW_SCHEMA"."V$CLUSTER_DISPATCHER"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$CLUSTER_LOCATION" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$CLUSTER_LOCATION"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$CLUSTER_LOCATION" FOR "PERFORMANCE_VIEW_SCHEMA"."V$CLUSTER_LOCATION"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$WAIT_EVENT_NAME" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$WAIT_EVENT_NAME"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$WAIT_EVENT_NAME" FOR "PERFORMANCE_VIEW_SCHEMA"."V$WAIT_EVENT_NAME"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$WAIT_EVENT_CLASS_NAME" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$WAIT_EVENT_CLASS_NAME"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$WAIT_EVENT_CLASS_NAME" FOR "PERFORMANCE_VIEW_SCHEMA"."V$WAIT_EVENT_CLASS_NAME"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SYSTEM_EVENT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SYSTEM_EVENT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SYSTEM_EVENT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SYSTEM_EVENT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SESSION_EVENT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SESSION_EVENT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SESSION_EVENT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SESSION_EVENT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SESSION_WAIT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SESSION_WAIT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SESSION_WAIT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SESSION_WAIT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$AGABLE_INFO" FOR "PERFORMANCE_VIEW_SCHEMA"."V$AGABLE_INFO"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SQL_HISTORY" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SQL_HISTORY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$AUDITABLE_DB_PRIVILEGES" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$AUDITABLE_DB_PRIVILEGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$AUDITABLE_DB_PRIVILEGES" FOR "PERFORMANCE_VIEW_SCHEMA"."V$AUDITABLE_DB_PRIVILEGES"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$AUDITABLE_SYSTEM_ACTIONS" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$AUDITABLE_SYSTEM_ACTIONS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$AUDITABLE_SYSTEM_ACTIONS" FOR "PERFORMANCE_VIEW_SCHEMA"."V$AUDITABLE_SYSTEM_ACTIONS"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$SEQUENCE" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$SEQUENCE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$SEQUENCE" FOR "PERFORMANCE_VIEW_SCHEMA"."V$SEQUENCE"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$BCH" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$BCH"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$BCH" FOR "PERFORMANCE_VIEW_SCHEMA"."V$BCH"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$BUFFER_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$BUFFER_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$BUFFER_STAT" FOR "PERFORMANCE_VIEW_SCHEMA"."V$BUFFER_STAT"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$DB_CHANGE_TRACKING" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$DB_CHANGE_TRACKING"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$DB_CHANGE_TRACKING" FOR "PERFORMANCE_VIEW_SCHEMA"."V$DB_CHANGE_TRACKING"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$PLAN_HISTORY" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$PLAN_HISTORY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$PLAN_HISTORY" FOR "PERFORMANCE_VIEW_SCHEMA"."V$PLAN_HISTORY"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "GV$PLAN_HISTORY_LATEST" FOR "PERFORMANCE_VIEW_SCHEMA"."GV$PLAN_HISTORY_LATEST"
;
COMMIT;

SET SESSION AUTHORIZATION "SYS"; 
CREATE PUBLIC SYNONYM "V$PLAN_HISTORY_LATEST" FOR "PERFORMANCE_VIEW_SCHEMA"."V$PLAN_HISTORY_LATEST"
;
COMMIT;

--##################################################### 
--# Table DDL 
--##################################################### 


SET SESSION AUTHORIZATION "SYS"; 
CREATE TABLE "PUBLIC"."DEDUCTION" 
    ( 
        "SNO" NUMBER
      , "SNAME" VARCHAR( 10 OCTETS )
      , "USE_AMT" NUMBER
      , "MOD_DATE" TIMESTAMP( 6 ) WITHOUT TIME ZONE
    ) 
    CLONED 
    AT CLUSTER WIDE 
    PCTFREE  10 
    PCTUSED  60 
    INITRANS 4 
    MAXTRANS 8 
    STORAGE 
    ( 
        INITIAL 524288 
        NEXT    262144 
        MINSIZE 524288 
        MAXSIZE 562949953159168 
    ) 
    TABLESPACE "MEM_DATA_TBS" 
    WITHOUT GLOBAL SECONDARY INDEX 
;
COMMIT;

SET SESSION AUTHORIZATION "TEST"; 
CREATE TABLE "PUBLIC"."CYCLONE_SLAVE_STATE" 
    ( 
        "GROUP_NAME" VARCHAR( 128 OCTETS )
      , "GROUP_SUB_ID" NUMBER( 10, 0 )
      , "APPLIER_ID" NUMBER( 10, 0 )
      , "RESTART_LSN" NUMBER( 19, 0 )
      , "LASTCOMMIT_LSN" NUMBER( 19, 0 )
      , "FILESEQ_NO" NUMBER( 19, 0 )
      , "GROUPID" NUMBER( 10, 0 )
      , "BLOCKSEQ" NUMBER( 10, 0 )
      , "LOGNO" NUMBER( 10, 0 )
      , "WRAPNO" NUMBER( 5, 0 )
      , "GCN" NUMBER( 20, 0 )
      , "DCN" NUMBER( 20, 0 )
      , "LCN" NUMBER( 20, 0 )
    ) 
    SHARDING BY HASH 
    ( 
        "GROUP_NAME" 
      , "GROUP_SUB_ID" 
      , "APPLIER_ID" 
    ) 
    SHARD COUNT 24 
    AT CLUSTER WIDE 
    PCTFREE  10 
    PCTUSED  60 
    INITRANS 4 
    MAXTRANS 8 
    STORAGE 
    ( 
        INITIAL 524288 
        NEXT    262144 
        MINSIZE 524288 
        MAXSIZE 562949953159168 
    ) 
    TABLESPACE "MEM_DATA_TBS" 
    WITHOUT GLOBAL SECONDARY INDEX 
;
COMMIT;

SET SESSION AUTHORIZATION "TEST"; 
CREATE TABLE "PUBLIC"."CYCLONE_SLAVE_TABLE" 
    ( 
        "GROUP_NAME" VARCHAR( 128 OCTETS )
      , "MASTER_SCHEMA" VARCHAR( 128 OCTETS )
      , "MASTER_TABLE" VARCHAR( 128 OCTETS )
      , "STARTSCN_GCN" NUMBER( 20, 0 )
      , "STARTSCN_DCN" NUMBER( 20, 0 )
      , "STARTSCN_LCN" NUMBER( 20, 0 )
      , "GIVEUPSCN_GCN" NUMBER( 20, 0 )
      , "GIVEUPSCN_DCN" NUMBER( 20, 0 )
      , "GIVEUPSCN_LCN" NUMBER( 20, 0 )
    ) 
    SHARDING BY HASH 
    ( 
        "GROUP_NAME" 
      , "MASTER_SCHEMA" 
      , "MASTER_TABLE" 
    ) 
    SHARD COUNT 24 
    AT CLUSTER WIDE 
    PCTFREE  10 
    PCTUSED  60 
    INITRANS 4 
    MAXTRANS 8 
    STORAGE 
    ( 
        INITIAL 524288 
        NEXT    262144 
        MINSIZE 524288 
        MAXSIZE 562949953159168 
    ) 
    TABLESPACE "MEM_DATA_TBS" 
    WITHOUT GLOBAL SECONDARY INDEX 
;
COMMIT;

--##################################################### 
--# Table Privilege DDL 
--##################################################### 


--##################################################### 
--# appropriate point for uploading data 
--##################################################### 


--##################################################### 
--# Table Option DDL 
--##################################################### 


--##################################################### 
--# Constraint DDL 
--##################################################### 


SET SESSION AUTHORIZATION "SYS"; 
ALTER TABLE "PUBLIC"."DEDUCTION" 
    ADD CONSTRAINT "PUBLIC"."DEDUCTION_PRIMARY_KEY" 
    PRIMARY KEY 
    ( 
        "SNO" ASC NULLS LAST
    ) 
    INDEX "DEDUCTION_PRIMARY_KEY_INDEX" 
    PCTFREE  0 
    INITRANS 4 
    MAXTRANS 8 
    STORAGE 
    ( 
        INITIAL 524288 
        NEXT    262144 
        MINSIZE 524288 
        MAXSIZE 562949953159168 
    ) 
    TABLESPACE "MEM_TEMP_TBS" 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;
COMMIT;

SET SESSION AUTHORIZATION "TEST"; 
ALTER TABLE "PUBLIC"."CYCLONE_SLAVE_STATE" 
    ADD CONSTRAINT "PUBLIC"."CYCLONE_SLAVE_STATE_PRIMARY_KEY" 
    PRIMARY KEY 
    ( 
        "GROUP_NAME" ASC NULLS LAST
      , "GROUP_SUB_ID" ASC NULLS LAST
      , "APPLIER_ID" ASC NULLS LAST
    ) 
    INDEX "CYCLONE_SLAVE_STATE_PRIMARY_KEY_INDEX" 
    PCTFREE  0 
    INITRANS 4 
    MAXTRANS 8 
    STORAGE 
    ( 
        INITIAL 524288 
        NEXT    262144 
        MINSIZE 524288 
        MAXSIZE 562949953159168 
    ) 
    TABLESPACE "MEM_TEMP_TBS" 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;
COMMIT;

SET SESSION AUTHORIZATION "TEST"; 
ALTER TABLE "PUBLIC"."CYCLONE_SLAVE_TABLE" 
    ADD CONSTRAINT "PUBLIC"."CYCLONE_SLAVE_TABLE_PRIMARY_KEY" 
    PRIMARY KEY 
    ( 
        "GROUP_NAME" ASC NULLS LAST
      , "MASTER_SCHEMA" ASC NULLS LAST
      , "MASTER_TABLE" ASC NULLS LAST
    ) 
    INDEX "CYCLONE_SLAVE_TABLE_PRIMARY_KEY_INDEX" 
    PCTFREE  0 
    INITRANS 4 
    MAXTRANS 8 
    STORAGE 
    ( 
        INITIAL 524288 
        NEXT    262144 
        MINSIZE 524288 
        MAXSIZE 562949953159168 
    ) 
    TABLESPACE "MEM_TEMP_TBS" 
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;
COMMIT;

--##################################################### 
--# Index DDL 
--##################################################### 


SET SESSION AUTHORIZATION "SYS"; 
ALTER TABLE "PUBLIC"."DEDUCTION" ADD GLOBAL SECONDARY INDEX 
    PCTFREE  0 
    INITRANS 4 
    MAXTRANS 8 
    STORAGE 
    ( 
        INITIAL 524288 
        NEXT    262144 
        MINSIZE 524288 
        MAXSIZE 562949953159168 
    ) 
    TABLESPACE "MEM_TEMP_TBS" 
;
COMMIT;

SET SESSION AUTHORIZATION "TEST"; 
ALTER TABLE "PUBLIC"."CYCLONE_SLAVE_STATE" ADD GLOBAL SECONDARY INDEX 
    PCTFREE  0 
    INITRANS 4 
    MAXTRANS 8 
    STORAGE 
    ( 
        INITIAL 524288 
        NEXT    262144 
        MINSIZE 524288 
        MAXSIZE 562949953159168 
    ) 
    TABLESPACE "MEM_TEMP_TBS" 
;
COMMIT;

SET SESSION AUTHORIZATION "TEST"; 
ALTER TABLE "PUBLIC"."CYCLONE_SLAVE_TABLE" ADD GLOBAL SECONDARY INDEX 
    PCTFREE  0 
    INITRANS 4 
    MAXTRANS 8 
    STORAGE 
    ( 
        INITIAL 524288 
        NEXT    262144 
        MINSIZE 524288 
        MAXSIZE 562949953159168 
    ) 
    TABLESPACE "MEM_TEMP_TBS" 
;
COMMIT;

--##################################################### 
--# View DDL 
--##################################################### 


--##################################################### 
--# View Privilege DDL 
--##################################################### 


--##################################################### 
--# Sequence DDL 
--##################################################### 


--##################################################### 
--# Sequence Privilege DDL 
--##################################################### 


--##################################################### 
--# Synonym DDL 
--##################################################### 


--##################################################### 
--# Procedure DDL 
--##################################################### 


--##################################################### 
--# Procedure Privilege DDL 
--##################################################### 


--##################################################### 
--# Package DDL 
--##################################################### 


--##################################################### 
--# Package Privilege DDL 
--##################################################### 


--##################################################### 
--# Audit Policy DDL 
--##################################################### 


