[T_PG_ADS_LTE_SESSION_INFO]
create table "T_PG_ADS_LTE_SESSION_INFO" ( 		
   "IDENTIFIER" VARCHAR(130),		
   "KEY_INDEX_P" VARCHAR(84) ,		
   "KEY_INDEX_S" VARCHAR(196) ,		
   "PAYLOAD" VARCHAR(1024) NOT NULL,		
   "OPEN_DATE" CHAR(8) ,		
   "OPEN_TIME" CHAR(6) ,		
   "UPDATE_TIME" DATE 		
)sharding by hash(IDENTIFIER);		

alter table "T_PG_ADS_LTE_SESSION_INFO" add constraint "T_PG_ADS_LTE_SESSION_INFO_PK" primary key("IDENTIFIER");		
create index "T_PG_ADS_LTE_SESSION_INFO_IDX01" on "T_PG_ADS_LTE_SESSION_INFO"("KEY_INDEX_P") ;		
create index "T_PG_ADS_LTE_SESSION_INFO_IDX02" on "T_PG_ADS_LTE_SESSION_INFO"("KEY_INDEX_S") ;		
create index "T_PG_ADS_LTE_SESSION_INFO_IDX03" on "T_PG_ADS_LTE_SESSION_INFO"("UPDATE_TIME") ;		

